spring.application.name=craftorder
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=America/Guayaquil
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/craftorder
spring.datasource.username=postgres
spring.datasource.password=root2025

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

resend.api.key=${RESEND_API_KEY}
app.url.base=${APP_BASE_URL:http://localhost:8091}
resend.from=Classic Muebler\u00EDa <onboarding@resend.dev>

taller.nombre=Classic Muebler\u00EDa
taller.ruc=1234567890001
taller.direccion=Quito, Ecuador
taller.telefono=0991234567
# taller.correo=
